"""VM2 (Litestream replica) bootstrap and resync tasks: pure script builders
(``_build_setup_replica_*``), the :func:`setup_replica` orchestrator, and
post-restore housekeeping (:func:`replica_resync`, :func:`replica_restore_db`)."""

from pathlib import Path

from invoke import task

from tasks.devtools.constants import (
    _REMOTE_DB_PATH,
    _REMOTE_LITESTREAM_SHADOW_PATH,
    BACKUP_FILENAME_PREFIX,
    BACKUP_FILENAME_SUFFIX,
    BACKUP_RCLONE_PATH,
    BACKUP_RCLONE_REMOTE,
    BACKUP_RETENTION_DAILY,
    BACKUP_RETENTION_MONTHLY,
    BACKUP_RETENTION_SCRIPT_PATH,
    BACKUP_RETENTION_WEEKLY,
    BACKUP_SCRIPT_PATH,
    BACKUP_SERVICE_PATH,
    BACKUP_TIMER_PATH,
    LITESTREAM_SERVICE,
    LITESTREAM_SNAPSHOT_INTERVAL,
    REMOTE_LITESTREAM_CONFIG_PATH,
    REPLICA_DB_NAME,
    REPLICA_LITESTREAM_DIR,
    VM1_LITESTREAM_KEY_PATH,
)
from tasks.devtools.env import litestream_retention, replica_host
from tasks.ssh_utils import (
    build_add_known_host_script,
    build_ensure_vm1_replica_key_script,
    build_harden_sshd_script,
    build_install_authorized_key_script,
    build_install_fail2ban_script,
    build_reset_known_host_script,
    build_setup_swap_script,
    create_service,
    litestream_install_script,
    ssh_capture,
    ssh_replica,
    ssh_replica_capture_bytes,
    ssh_run,
    ssh_sudo,
    write_remote_file,
    write_remote_replica_file,
)

from .backups_yandex import ensure_yandex_rclone_configured
from .restore_utils import apply_restore, confirm_overwrite, litestream_active, local_replica_resync


def _replica_sftp_host() -> str:
    """Strips the ``user@`` prefix to match what Litestream puts in known_hosts."""
    return replica_host().split("@", 1)[-1]


def _build_litestream_config() -> str:
    """All values derived from ``.deploy/.env`` + constants — no manual template.

    ``concurrent-writes: false`` trades throughput we do not need on a ~1.5 MB database for
    uploads that resume after a failed chunk instead of being re-sent from scratch.
    """
    rhost = replica_host()
    if "@" in rhost:
        user, host_part = rhost.split("@", 1)
    else:
        user = "ubuntu"
        host_part = rhost
    return (
        "# Generated by inv setup-replica. Do not edit by hand.\n"
        "\n"
        "snapshot:\n"
        f"  interval: {LITESTREAM_SNAPSHOT_INTERVAL}\n"
        f"  retention: {litestream_retention()}\n"
        "\n"
        "dbs:\n"
        f"  - path: {_REMOTE_DB_PATH}\n"
        "    replica:\n"
        "      type: sftp\n"
        f"      host: {host_part}:22\n"
        f"      user: {user}\n"
        f"      key-path: {VM1_LITESTREAM_KEY_PATH}\n"
        f"      path: {REPLICA_LITESTREAM_DIR}/{REPLICA_DB_NAME}\n"
        "      concurrent-writes: false\n"
    )


def _build_setup_replica_packages_script() -> str:
    """``DEBIAN_FRONTEND=noninteractive`` is required — without it a fresh Ubuntu
    image can block forever on a postfix/grub debconf prompt."""
    return (
        "sudo bash <<'DINARY_REPLICA_PKG_EOF'\n"
        "set -euo pipefail\n"
        "export DEBIAN_FRONTEND=noninteractive\n"
        "apt-get update -qq\n"
        "apt-get install -y -qq unattended-upgrades\n"
        "DINARY_REPLICA_PKG_EOF\n"
    )


def _build_setup_replica_litestream_dir_script() -> str:
    """Mode ``0750``/``ubuntu:ubuntu`` lets the SFTP receiver write WAL segments
    without granting world-read to the replica stream (full row data pre-compaction)."""
    return (
        "sudo bash <<'DINARY_REPLICA_DIR_EOF'\n"
        "set -euo pipefail\n"
        f"mkdir -p {REPLICA_LITESTREAM_DIR}\n"
        f"chown ubuntu:ubuntu {REPLICA_LITESTREAM_DIR}\n"
        f"chmod 750 {REPLICA_LITESTREAM_DIR}\n"
        f"ls -ld {REPLICA_LITESTREAM_DIR}\n"
        "DINARY_REPLICA_DIR_EOF\n"
    )


def _build_setup_replica_backup_packages_script() -> str:
    """Emit the apt step that installs backup tools on VM2 (rclone, sqlite3, zstd)."""
    return (
        "sudo bash <<'DINARY_BACKUP_PKG_EOF'\n"
        "set -euo pipefail\n"
        "export DEBIAN_FRONTEND=noninteractive\n"
        "apt-get update -qq\n"
        "apt-get install -y -qq python3 rclone sqlite3 zstd\n"
        "DINARY_BACKUP_PKG_EOF\n"
    )


def _build_backup_script() -> str:
    """Flow: litestream restore -> integrity_check -> zstd -> rclone copyto -> retention
    prune. ``set -euo pipefail`` + trap ensures a failed restore never leaks temp
    files or overwrites Yandex history with a corrupt snapshot."""
    replica_path = f"{REPLICA_LITESTREAM_DIR}/{REPLICA_DB_NAME}"
    remote_prefix = f"{BACKUP_RCLONE_REMOTE}:{BACKUP_RCLONE_PATH}"
    return f"""#!/usr/bin/env bash
# Managed by inv setup-replica. Overwritten on every re-apply.
set -euo pipefail

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT

SNAP="$WORKDIR/dinary.db"
CFG="$WORKDIR/litestream-restore.yml"

cat > "$CFG" <<YAML
dbs:
  - path: $SNAP
    replicas:
      - type: file
        path: {replica_path}
YAML

litestream restore -config "$CFG" "$SNAP"

if ! sqlite3 "$SNAP" 'PRAGMA integrity_check' | grep -qx 'ok'; then
    echo "integrity_check FAILED on restored snapshot" >&2
    exit 1
fi

zstd -q -19 "$SNAP" -o "$SNAP.zst"

TS=$(date -u +%Y-%m-%dT%H%MZ)
REMOTE="{remote_prefix}/{BACKUP_FILENAME_PREFIX}$TS{BACKUP_FILENAME_SUFFIX}"
rclone copyto "$SNAP.zst" "$REMOTE"

{BACKUP_RETENTION_SCRIPT_PATH} \\
    --remote "{remote_prefix}/" \\
    --prefix "{BACKUP_FILENAME_PREFIX}" \\
    --suffix "{BACKUP_FILENAME_SUFFIX}" \\
    --daily {BACKUP_RETENTION_DAILY} \\
    --weekly {BACKUP_RETENTION_WEEKLY} \\
    --monthly {BACKUP_RETENTION_MONTHLY}
"""


def _build_backup_service_unit() -> str:
    """Emit the ``dinary-backup.service`` systemd oneshot unit for VM2."""
    return (
        "# Managed by inv setup-replica. Overwritten on every re-apply.\n"
        "[Unit]\n"
        "Description=Back up dinary replica to Yandex.Disk\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=oneshot\n"
        "User=ubuntu\n"
        f"ExecStart={BACKUP_SCRIPT_PATH}\n"
        "Nice=10\n"
        "IOSchedulingClass=best-effort\n"
        "IOSchedulingPriority=7\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


def _build_backup_timer_unit() -> str:
    """03:17 UTC with 30m jitter avoids top-of-hour Litestream cadence;
    ``Persistent=true`` catches missed runs so the 24h retention gap can't open."""
    return (
        "# Managed by inv setup-replica. Overwritten on every re-apply.\n"
        "[Unit]\n"
        "Description=Daily dinary off-site backup\n"
        "\n"
        "[Timer]\n"
        "OnCalendar=*-*-* 03:17:00\n"
        "RandomizedDelaySec=30m\n"
        "Persistent=true\n"
        "\n"
        "[Install]\n"
        "WantedBy=timers.target\n"
    )


@task(name="setup-replica")
def setup_replica(c, swap_size_gb=1, no_swap=False):
    """Bootstrap VM2 (Litestream SFTP replica) and configure VM1 replication. Idempotent.

    Requires DINARY_REPLICA_HOST in .deploy/.env. Also installs daily Yandex.Disk backup on VM2.
    See https://andgineer.github.io/dinary/operations for the full replica setup guide.

    --swap-size-gb N (default 1), --no-swap to skip.
    """
    size = int(swap_size_gb)
    print(f"=== Installing baseline packages on {replica_host()} ===")
    ssh_replica(c, _build_setup_replica_packages_script())
    print(f"=== Hardening sshd on {replica_host()} ===")
    ssh_replica(c, build_harden_sshd_script())
    print(f"=== Installing fail2ban on {replica_host()} ===")
    ssh_replica(c, build_install_fail2ban_script())
    print(f"=== Provisioning {REPLICA_LITESTREAM_DIR} ===")
    ssh_replica(c, _build_setup_replica_litestream_dir_script())
    if not no_swap:
        print("=== Allocating swap on VM2 ===")
        ssh_replica(c, build_setup_swap_script(size_gb=size))

    print(f"=== Installing backup packages (rclone, sqlite3, zstd) on {replica_host()} ===")
    ssh_replica(c, _build_setup_replica_backup_packages_script())
    print(f"=== Installing Litestream binary on {replica_host()} ===")
    ssh_replica(c, litestream_install_script())

    print(f"=== Configuring Yandex.Disk rclone remote on {replica_host()} ===")
    ensure_yandex_rclone_configured(c)

    print(f"=== Installing backup script on {replica_host()} ===")
    write_remote_replica_file(c, BACKUP_SCRIPT_PATH, _build_backup_script())
    ssh_replica(c, f"sudo chmod 0755 {BACKUP_SCRIPT_PATH}")
    retention_src = (Path(__file__).parent / "backup_retention.py").read_text(
        encoding="utf-8",
    )
    write_remote_replica_file(c, BACKUP_RETENTION_SCRIPT_PATH, retention_src)
    ssh_replica(c, f"sudo chmod 0755 {BACKUP_RETENTION_SCRIPT_PATH}")
    write_remote_replica_file(c, BACKUP_SERVICE_PATH, _build_backup_service_unit())
    write_remote_replica_file(c, BACKUP_TIMER_PATH, _build_backup_timer_unit())
    ssh_replica(c, "sudo systemctl daemon-reload")
    ssh_replica(c, "sudo systemctl enable --now dinary-backup.timer")

    print("=== Configuring VM1 Litestream replicator ===")
    content = _build_litestream_config()

    print("=== Establishing VM1→VM2 SSH trust for Litestream SFTP ===")
    pubkey = ssh_capture(c, build_ensure_vm1_replica_key_script()).strip()
    ssh_replica(c, build_install_authorized_key_script(pubkey))
    ssh_run(c, build_add_known_host_script(_replica_sftp_host()))

    ssh_run(c, litestream_install_script())
    write_remote_file(c, REMOTE_LITESTREAM_CONFIG_PATH, content)
    ssh_sudo(
        c,
        f"bash -c 'chown root:root {REMOTE_LITESTREAM_CONFIG_PATH} "
        f"&& chmod 644 {REMOTE_LITESTREAM_CONFIG_PATH}'",
    )
    create_service(c, "litestream", LITESTREAM_SERVICE)
    # `enable --now` is a no-op on an already-running unit, so a re-apply would keep the
    # old binary and the old config live until the next reboot.
    ssh_sudo(c, "systemctl restart litestream")
    ssh_run(
        c,
        "sleep 3 && systemctl is-active litestream && "
        "sudo journalctl -u litestream -n 20 --no-pager",
    )

    print("=== Replica bootstrap done ===")


@task(name="setup-reset-trust")
def replica_reset_trust(c):
    """Refresh VM1→VM2 SSH trust after an intentional VM2 reinstall.

    Run after VM2 is reprovisioned. Do not use for unexpected host-key mismatches.
    See https://andgineer.github.io/dinary/operations for the full procedure.
    """
    lite_host = _replica_sftp_host()
    print(f"=== Resetting VM2 host key ({lite_host}) in VM1 known_hosts ===")
    ssh_run(c, build_reset_known_host_script(lite_host))
    print("=== Re-installing VM1 pubkey on VM2 authorized_keys ===")
    pubkey = ssh_capture(c, build_ensure_vm1_replica_key_script()).strip()
    ssh_replica(c, build_install_authorized_key_script(pubkey))
    print("=== Trust refreshed ===")


def _build_replica_restore_script(timestamp: str | None) -> str:
    """Emit a bash script that restores from VM2's LTX archive and writes the DB to stdout."""
    replica_path = f"{REPLICA_LITESTREAM_DIR}/{REPLICA_DB_NAME}"
    ts_args = f' -timestamp "{timestamp}"' if timestamp else ""
    return (
        "set -euo pipefail\n"
        "WORKDIR=$(mktemp -d)\n"
        "trap 'rm -rf \"$WORKDIR\"' EXIT\n"
        'SNAP="$WORKDIR/dinary.db"\n'
        'CFG="$WORKDIR/ls.yml"\n'
        'cat > "$CFG" <<LSYAML\n'
        "dbs:\n"
        "  - path: $SNAP\n"
        "    replicas:\n"
        "      - type: file\n"
        f"        path: {replica_path}\n"
        "LSYAML\n"
        f'litestream restore -config "$CFG"{ts_args} "$SNAP" >&2\n'
        'cat "$SNAP"\n'
    )


@task(name="replica-resync")
def replica_resync(c):
    """Resync VM2 replica after a DB restore or WAL txid mismatch.

    Runs automatically after restore tasks unless --no-resync is passed.
    See https://andgineer.github.io/dinary/operations for when to run manually.
    """
    print("=== Stopping litestream on VM1 ===")
    ssh_run(c, "sudo systemctl stop litestream")
    print("=== Wiping stale LTX shadow tree on VM1 ===")
    ssh_run(c, f"rm -rf {_REMOTE_LITESTREAM_SHADOW_PATH}")
    print(f"=== Wiping stale LTX tree on {replica_host()} ===")
    ssh_replica(c, f"rm -rf {REPLICA_LITESTREAM_DIR}/{REPLICA_DB_NAME}")
    print("=== Starting litestream on VM1 (will push fresh snapshot) ===")
    ssh_run(c, "sudo systemctl start litestream")
    ssh_run(
        c,
        "sleep 5 && systemctl is-active litestream && "
        "sudo journalctl -u litestream -n 20 --no-pager",
    )
    print("=== Replica resync done ===")


@task(name="restore-replica")
def restore_replica(c, output=None, yes=False, timestamp=None, no_resync=False):
    """Restore a snapshot from VM2's Litestream LTX archive to data/dinary.db.

    More current than restore-yadisk (WAL-level vs daily Yandex.Disk).
    Flags: -o PATH, --yes, --timestamp ISO8601 (default: latest), --no-resync.
    See https://andgineer.github.io/dinary/operations for restore runbooks.
    """
    target = Path(output) if output else Path("data/dinary.db")
    incoming_desc = (
        f"snapshot from VM2 LTX archive at {timestamp}"
        if timestamp
        else "latest snapshot from VM2 LTX archive"
    )
    if target.exists() and target.stat().st_size > 0:
        confirm_overwrite(target, incoming_desc, yes)
    print(f"=== Restoring from {replica_host()} LTX archive ===")
    if timestamp:
        print(f"=== Point-in-time: {timestamp} ===")
    db_bytes = ssh_replica_capture_bytes(_build_replica_restore_script(timestamp))
    apply_restore(db_bytes, target)
    print(f"=== Restored {len(db_bytes) / 1024:.1f} KB → {target} ===")
    if litestream_active() and not no_resync:
        local_replica_resync(c)
