"""Constants for all task modules: paths, service templates, version pins."""

from tasks.backups.backup_snapshots import (
    BACKUP_FILENAME_PREFIX,
    BACKUP_FILENAME_SUFFIX,
    BACKUP_RCLONE_PATH,
    BACKUP_RCLONE_REMOTE,
    BACKUP_STALE_HOURS,
)

ALLOWED_VERSION_TYPES = ["release", "bug", "feature"]

REPO_URL = "https://github.com/andgineer/dinary.git"

_UV = "/home/ubuntu/.local/bin/uv"
# Calls the venv's uvicorn directly, not `uv run uvicorn` — `uv run`'s
# ~/.cache/uv write on startup conflicts with ProtectHome=read-only below.
_DINARY_UVICORN = "/home/ubuntu/dinary/.venv/bin/uvicorn"
_DINARY_EXEC = (
    "ExecStart=/bin/sh -c 'exec " + _DINARY_UVICORN + " dinary.main:app --host {host} --port 8000'"
)

# network.target doesn't wait for tailscaled (seen in practice after a reboot),
# so this blocks startup until it's ready.
_DINARY_EXEC_START_PRE_TAILSCALE = (
    "ExecStartPre=/bin/sh -c 'for i in $(seq 1 30); do "
    "tailscale ip -4 >/dev/null 2>&1 && exit 0; sleep 1; done; exit 1'"
)

# Confines the app to the minimum authority it needs so a code-exec bug in a
# dependency can't read secrets outside ~/dinary or touch system state.
_DINARY_SANDBOX = (
    "NoNewPrivileges=true\n"
    "ProtectSystem=strict\n"
    "ProtectHome=read-only\n"
    "ReadWritePaths=/home/ubuntu/dinary/data\n"
    "PrivateTmp=true\n"
    "ProtectKernelTunables=true\n"
    "ProtectKernelModules=true\n"
    "ProtectKernelLogs=true\n"
    "ProtectControlGroups=true\n"
    "RestrictSUIDSGID=true\n"
    "RestrictRealtime=true\n"
    "RestrictNamespaces=true\n"
    "LockPersonality=true\n"
    "MemoryDenyWriteExecute=true\n"
    "SystemCallArchitectures=native\n"
    "CapabilityBoundingSet=\n"
    "AmbientCapabilities=\n"
)

DINARY_SERVICE = (
    "[Unit]\nDescription=dinary\n"
    "After=network-online.target tailscaled.service\n"
    "Wants=network-online.target tailscaled.service\n\n"
    "[Service]\nType=simple\nUser=ubuntu\n"
    "WorkingDirectory=/home/ubuntu/dinary\n"
    "EnvironmentFile=/home/ubuntu/dinary/.deploy/.env\n"
    + _DINARY_EXEC_START_PRE_TAILSCALE
    + "\n"
    + _DINARY_EXEC
    + "\nRestart=always\nRestartSec=5\n"
    + _DINARY_SANDBOX
    + "\n[Install]\nWantedBy=multi-user.target\n"
)

CLOUDFLARED_SERVICE = """\
[Unit]
Description=Cloudflare Tunnel for dinary
After=network.target

[Service]
Type=simple
User=ubuntu
ExecStart=/usr/bin/cloudflared tunnel run
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"""

# User=ubuntu matches the app service so the sidecar can read WAL segments
# without sudo.
LITESTREAM_SERVICE = (
    "[Unit]\nDescription=Litestream replicator for dinary\n"
    "After=network-online.target tailscaled.service\n"
    "Wants=network-online.target tailscaled.service\n\n"
    "[Service]\nType=simple\nUser=ubuntu\n"
    "ExecStartPre=/bin/sh -c 'for i in $(seq 1 30); do "
    "tailscale ip -4 >/dev/null 2>&1 && exit 0; sleep 1; done; exit 1'\n"
    "ExecStart=/usr/bin/litestream replicate -config /etc/litestream.yml\n"
    "Restart=always\nRestartSec=5\n"
    "NoNewPrivileges=true\n"
    "ProtectSystem=strict\n"
    "ProtectHome=read-only\n"
    # Needs to write its shadow WAL next to the live DB on VM1;
    # /var/lib/litestream only exists on VM2 (the SFTP receive tree).
    "ReadWritePaths=/home/ubuntu/dinary/data\n"
    "PrivateTmp=true\n"
    "ProtectKernelTunables=true\n"
    "ProtectKernelModules=true\n"
    "ProtectKernelLogs=true\n"
    "ProtectControlGroups=true\n"
    "RestrictSUIDSGID=true\n"
    "RestrictRealtime=true\n"
    "RestrictNamespaces=true\n"
    "LockPersonality=true\n"
    "SystemCallArchitectures=native\n"
    "CapabilityBoundingSet=\n"
    "AmbientCapabilities=\n"
    "\n[Install]\nWantedBy=multi-user.target\n"
)

VALID_TUNNELS = ("tailscale", "cloudflare", "none")

LOCAL_ENV_PATH = ".deploy/.env"
LOCAL_ENV_EXAMPLE_PATH = ".deploy.example/.env"
REMOTE_DEPLOY_DIR = "/home/ubuntu/dinary/.deploy"
REMOTE_ENV_PATH = f"{REMOTE_DEPLOY_DIR}/.env"
REMOTE_LITESTREAM_CONFIG_PATH = "/etc/litestream.yml"

# Module-level (not inlined into the shell script) so a version bump is a
# one-line diff that can't drift out of sync with the asset filenames.
LITESTREAM_VERSION = "0.5.1"

# SSH key pair generated by ``inv setup-replica`` on VM1 and added to
# VM2's authorized_keys for the Litestream SFTP connection.
VM1_LITESTREAM_KEY_PATH = "/home/ubuntu/.ssh/id_ed25519"

# Litestream snapshot cadence. Bounds the LTX replay time on
# ``litestream restore`` to at most one interval.
LITESTREAM_SNAPSHOT_INTERVAL = "1h"

REPLICA_LITESTREAM_DIR = "/var/lib/litestream"

# Must match the trailing segment of the generated litestream.yml's `path:` —
# drift here would restore from the wrong replica tree.
REPLICA_DB_NAME = "dinary"

# Off-site backup to Yandex.Disk, see docs/src/en/operations.md.
BACKUP_SCRIPT_PATH = "/usr/local/bin/dinary-backup"
BACKUP_RETENTION_SCRIPT_PATH = "/usr/local/bin/dinary-backup-retention"
BACKUP_SERVICE_PATH = "/etc/systemd/system/dinary-backup.service"
BACKUP_TIMER_PATH = "/etc/systemd/system/dinary-backup.timer"

# GFS retention. Closed years are immutable, so yearly snapshots are kept
# indefinitely — a drift between two of the same closed year is a corruption
# signal worth retaining forever.
BACKUP_RETENTION_DAILY = 7
BACKUP_RETENTION_WEEKLY = 4
BACKUP_RETENTION_MONTHLY = 12

#: Remote path of the live SQLite ledger file.
_REMOTE_DB_PATH = "/home/ubuntu/dinary/data/dinary.db"

# Litestream's local LTX shadow tree on VM1, named after the DB file. It holds txids from
# whichever database it was built against, so replacing the DB strands it: litestream then
# asks for segments the tree never had and every sync fails. A resync must clear this side
# too — wiping only VM2 leaves the stale tree in place and the replica stays broken.
_REMOTE_LITESTREAM_SHADOW_PATH = "/home/ubuntu/dinary/data/.dinary.db-litestream"

# Re-export so consumers of this module get the full set in one import.
__all__ = [
    "ALLOWED_VERSION_TYPES",
    "BACKUP_FILENAME_PREFIX",
    "BACKUP_FILENAME_SUFFIX",
    "BACKUP_RETENTION_DAILY",
    "BACKUP_RETENTION_MONTHLY",
    "BACKUP_RETENTION_SCRIPT_PATH",
    "BACKUP_RETENTION_WEEKLY",
    "BACKUP_RCLONE_PATH",
    "BACKUP_RCLONE_REMOTE",
    "BACKUP_SCRIPT_PATH",
    "BACKUP_SERVICE_PATH",
    "BACKUP_STALE_HOURS",
    "BACKUP_TIMER_PATH",
    "CLOUDFLARED_SERVICE",
    "DINARY_SERVICE",
    "LITESTREAM_SERVICE",
    "LITESTREAM_SNAPSHOT_INTERVAL",
    "LITESTREAM_VERSION",
    "LOCAL_ENV_EXAMPLE_PATH",
    "LOCAL_ENV_PATH",
    "REMOTE_DEPLOY_DIR",
    "VM1_LITESTREAM_KEY_PATH",
    "REMOTE_ENV_PATH",
    "REMOTE_LITESTREAM_CONFIG_PATH",
    "REPLICA_DB_NAME",
    "REPLICA_LITESTREAM_DIR",
    "REPO_URL",
    "VALID_TUNNELS",
    "_REMOTE_DB_PATH",
    "_REMOTE_LITESTREAM_SHADOW_PATH",
]
