"""Tests for restore_utils: litestream_active, _parse_vm2_ssh_target, local_replica_resync."""

from unittest.mock import MagicMock

import allure
import pytest

import tasks.backups.restore_utils as ru


_SAMPLE_CONFIG = """\
# Generated by inv setup-replica. Do not edit by hand.

snapshot:
  interval: 1h
  retention: 168h

dbs:
  - path: /home/ubuntu/dinary/data/dinary.db
    replica:
      type: sftp
      host: replica.example.com:22
      user: ubuntu
      key-path: /home/ubuntu/.ssh/id_ed25519
      path: /var/lib/litestream/dinary
"""


@allure.epic("Infrastructure")
@allure.feature("Backup")
@allure.story("Restore utils")
class TestLitestreamActive:
    def test_returns_true_when_service_running(self, monkeypatch):
        """returncode 0 from systemctl is-active means litestream is running."""
        fake = MagicMock(returncode=0)
        monkeypatch.setattr(ru.subprocess, "run", lambda *a, **kw: fake)
        assert ru.litestream_active() is True

    def test_returns_false_when_service_stopped(self, monkeypatch):
        """returncode 3 (inactive) must not be treated as active."""
        fake = MagicMock(returncode=3)
        monkeypatch.setattr(ru.subprocess, "run", lambda *a, **kw: fake)
        assert ru.litestream_active() is False

    def test_passes_correct_systemctl_args(self, monkeypatch):
        """The quiet flag must be present so the check is non-interactive."""
        captured = {}
        fake = MagicMock(returncode=0)

        def spy(args, **kw):
            captured["args"] = args
            return fake

        monkeypatch.setattr(ru.subprocess, "run", spy)
        ru.litestream_active()
        assert captured["args"] == ["systemctl", "is-active", "--quiet", "litestream"]


@allure.epic("Infrastructure")
@allure.feature("Backup")
@allure.story("Restore utils")
class TestParseVm2SshTarget:
    def test_extracts_user_at_host(self, tmp_path):
        """Happy path: returns ``user@host`` stripping the ``:22`` port."""
        cfg = tmp_path / "litestream.yml"
        cfg.write_text(_SAMPLE_CONFIG)
        assert ru._parse_vm2_ssh_target(cfg) == "ubuntu@replica.example.com"

    def test_strips_port_suffix(self, tmp_path):
        """``:22`` must be stripped; SSH does not want it in the host arg."""
        cfg = tmp_path / "litestream.yml"
        cfg.write_text(_SAMPLE_CONFIG)
        target = ru._parse_vm2_ssh_target(cfg)
        assert ":22" not in target

    def test_raises_on_missing_host(self, tmp_path):
        """A config without a ``host:`` line (e.g. non-SFTP replica) must raise ValueError."""
        cfg = tmp_path / "litestream.yml"
        cfg.write_text("dbs:\n  - path: /tmp/db\n    replica:\n      type: s3\n")
        with pytest.raises(ValueError, match="Cannot parse VM2 SSH target"):
            ru._parse_vm2_ssh_target(cfg)

    def test_raises_on_missing_user(self, tmp_path):
        """A config without a ``user:`` line must raise ValueError."""
        cfg = tmp_path / "litestream.yml"
        cfg.write_text("dbs:\n  - path: /tmp/db\n    replica:\n      host: h:22\n")
        with pytest.raises(ValueError, match="Cannot parse VM2 SSH target"):
            ru._parse_vm2_ssh_target(cfg)


@allure.epic("Infrastructure")
@allure.feature("Backup")
@allure.story("Restore utils")
class TestLocalReplicaResync:
    @pytest.fixture
    def _config(self, tmp_path, monkeypatch):
        cfg = tmp_path / "litestream.yml"
        cfg.write_text(_SAMPLE_CONFIG)
        monkeypatch.setattr(ru, "_LITESTREAM_CONFIG", cfg)
        return cfg

    @staticmethod
    def _vm2_wipe(c) -> str:
        return next(
            call_args[0][0]
            for call_args in c.run.call_args_list
            if "rm -rf" in call_args[0][0] and "ssh" in call_args[0][0]
        )

    @staticmethod
    def _vm1_wipe(c) -> str:
        return next(
            call_args[0][0]
            for call_args in c.run.call_args_list
            if "rm -rf" in call_args[0][0] and "ssh" not in call_args[0][0]
        )

    def test_stop_wipe_start_sequence(self, _config):
        """Resync must stop litestream, wipe both sides, then start litestream — in that order."""
        c = MagicMock()
        ru.local_replica_resync(c)
        cmds = [call_args[0][0] for call_args in c.run.call_args_list]
        stop_idx = next(i for i, cmd in enumerate(cmds) if "stop litestream" in cmd)
        wipe_idxs = [i for i, cmd in enumerate(cmds) if "rm -rf" in cmd]
        start_idx = next(i for i, cmd in enumerate(cmds) if "start litestream" in cmd)
        assert len(wipe_idxs) == 2
        assert stop_idx < min(wipe_idxs)
        assert max(wipe_idxs) < start_idx

    def test_wipes_vm1_shadow_tree(self, _config):
        """Wiping only VM2 strands VM1's shadow tree at the old txids and the replica stays broken."""
        c = MagicMock()
        ru.local_replica_resync(c)
        assert ru._REMOTE_LITESTREAM_SHADOW_PATH in self._vm1_wipe(c)

    def test_vm1_shadow_wipe_runs_locally_not_over_ssh(self, _config):
        """local_replica_resync already runs on VM1 — the shadow wipe must not be routed to VM2."""
        c = MagicMock()
        ru.local_replica_resync(c)
        assert "ssh" not in self._vm1_wipe(c)

    def test_wipe_uses_litestream_key(self, _config):
        """The SSH wipe command must use VM1_LITESTREAM_KEY_PATH, not a different key."""
        c = MagicMock()
        ru.local_replica_resync(c)
        assert ru.VM1_LITESTREAM_KEY_PATH in self._vm2_wipe(c)

    def test_wipe_targets_correct_vm2_host(self, _config):
        """The SSH wipe command must target the host parsed from litestream.yml."""
        c = MagicMock()
        ru.local_replica_resync(c)
        assert "ubuntu@replica.example.com" in self._vm2_wipe(c)

    def test_wipe_removes_replica_db_dir(self, _config):
        """The wipe must target REPLICA_LITESTREAM_DIR/REPLICA_DB_NAME, not a broader path."""
        c = MagicMock()
        ru.local_replica_resync(c)
        expected_path = f"{ru.REPLICA_LITESTREAM_DIR}/{ru.REPLICA_DB_NAME}"
        assert expected_path in self._vm2_wipe(c)
